# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/cfbf4459-2169-4b00-b50a-3683d16a6c99";
      fsType = "btrfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/81FC-4D70";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/b70c7f4a-ebdf-4b87-8583-7e0619b4708d"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-c10abb802fb0.useDHCP = lib.mkDefault true;
  # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
  # networking.interfaces.eth0.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth1661f85.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth1e9ab3a.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth341cb20.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth3c32aa5.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth52496d4.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth696ebad.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth85d42d8.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethadf456b.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethae41da0.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethc385a98.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethd45241a.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethfd4bc4a.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlan0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
