# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "mpt3sas" "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/8a3ce7cd-8bb5-4178-a6a8-a6b6e6e40eff";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/8a3ce7cd-8bb5-4178-a6a8-a6b6e6e40eff";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/8a3ce7cd-8bb5-4178-a6a8-a6b6e6e40eff";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/srv/nfs" =
    { device = "/dev/disk/by-uuid/8a3ce7cd-8bb5-4178-a6a8-a6b6e6e40eff";
      fsType = "btrfs";
      options = [ "subvol=srv/nfs" ];
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/8a3ce7cd-8bb5-4178-a6a8-a6b6e6e40eff";
      fsType = "btrfs";
      options = [ "subvol=swap" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/DCA2-BCDF";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  # fileSystems."/storage" =
  #   { device = "tank/storage";
  #     fsType = "zfs";
  #     options = [ "zfsutil" ];
  #   };

  # fileSystems."/media" =
  #   { device = "/dev/disk/by-uuid/475844a1-03c7-4be3-aabd-737e116aed0b";
  #     fsType = "xfs";
  #   };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
