[identities]
user = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL+GEANHFLqzCD6r4tLtkgAxoy+YEGt+lF6HFtApUuTV donkeykongreimer@gmail.com"
host = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEr877uNZJR3mXHJbcTuKamKvaJwobHt04vgmN666bhp root@pigs-desktop"

[[paths]]
glob = "*.age"
identities = ["user", "host"]
