[identities]
user = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL+GEANHFLqzCD6r4tLtkgAxoy+YEGt+lF6HFtApUuTV donkeykongreimer@gmail.com"
host = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID5TIg5X66lTGEdTxCx+1V/C8I3wdxCfysDp07lcwdgP root@pigs-laptop"

[[paths]]
glob = "*.age"
identities = ["user", "host"]
